name: ACU

on:
  push:
    branches:
      - main

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test step
        run: echo ${{ github.event.head_commit.message }}
      - name: Update Readme
        run: python update_readme.py
      - name: Update templates
        run: python update_template.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: (ACU) ${{ github.event.head_commit.message }}
          add_files: "README.md"
